ALTER TABLE workers ADD COLUMN IF NOT EXISTS user_id UUID;

ALTER TABLE workers ADD COLUMN IF NOT EXISTS profile_image_url VARCHAR(500);

ALTER TABLE workers ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS area VARCHAR(100);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE workers ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

ALTER TABLE workers ADD COLUMN IF NOT EXISTS price_per_meter DECIMAL(10,2);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS price_per_day DECIMAL(10,2);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS price_per_visit DECIMAL(10,2);

ALTER TABLE workers ADD COLUMN IF NOT EXISTS works_at_night BOOLEAN DEFAULT FALSE;
ALTER TABLE workers ADD COLUMN IF NOT EXISTS estimated_completion_days INTEGER;

ALTER TABLE workers ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE workers ADD COLUMN IF NOT EXISTS verification_status VARCHAR(50);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS id_card_number VARCHAR(50);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS id_card_image_url VARCHAR(500);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS license_number VARCHAR(50);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS license_image_url VARCHAR(500);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS certificate_urls TEXT;
ALTER TABLE workers ADD COLUMN IF NOT EXISTS verification_notes TEXT;
ALTER TABLE workers ADD COLUMN IF NOT EXISTS verified_at TIMESTAMP;
ALTER TABLE workers ADD COLUMN IF NOT EXISTS verified_by_admin_id UUID;

ALTER TABLE workers ADD COLUMN IF NOT EXISTS syndicate_id VARCHAR(50);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS syndicate_card_url VARCHAR(500);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS degree VARCHAR(100);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS degree_certificate_url VARCHAR(500);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS specialization VARCHAR(100);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS completed_projects_count INTEGER DEFAULT 0;

ALTER TABLE workers ADD COLUMN IF NOT EXISTS contractor_license VARCHAR(50);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS contractor_license_url VARCHAR(500);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS license_type VARCHAR(10);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS license_expiry_date DATE;
ALTER TABLE workers ADD COLUMN IF NOT EXISTS capital DECIMAL(15,2);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS employees_count INTEGER;
ALTER TABLE workers ADD COLUMN IF NOT EXISTS current_projects_count INTEGER DEFAULT 0;

ALTER TABLE workers ADD COLUMN IF NOT EXISTS design_type VARCHAR(50);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS software_skills TEXT;
ALTER TABLE workers ADD COLUMN IF NOT EXISTS portfolio_url VARCHAR(500);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS design_style VARCHAR(50);

ALTER TABLE workers ADD COLUMN IF NOT EXISTS specialized_experience_years INTEGER;
ALTER TABLE workers ADD COLUMN IF NOT EXISTS awards TEXT;
ALTER TABLE workers ADD COLUMN IF NOT EXISTS languages VARCHAR(255);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS working_hours VARCHAR(100);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS minimum_project_budget DECIMAL(15,2);

ALTER TABLE workers ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE workers ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);
